entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"

providers:
  file:
    directory: "/config"
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik
    watch: true
    exposedByDefault: false

certificatesResolvers:
  lets-encrypt:
    acme:
      email: yourname@example.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web 
